import React, { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { X, Play, RefreshCw, Layers, CheckCircle2, Copy, FileText, MapPin, Camera, AlertCircle, BarChart, Cpu, Info } from 'lucide-react';
import { Project } from '../types';

interface DemoModalProps {
  isOpen: boolean;
  project: Project | null;
  onClose: () => void;
}

export default function DemoModal({ isOpen, project, onClose }: DemoModalProps) {
  const [activeTab, setActiveTab] = useState<'case-select' | 'processing' | 'results'>('case-select');
  const [selectedCaseIdx, setSelectedCaseIdx] = useState(0);
  const [customText, setCustomText] = useState('');
  const [selectedModels, setSelectedModels] = useState({
    logisticRegression: true,
    naiveBayes: true,
    xgboost: true,
    bilstm: true,
  });

  // Legal pre-set cases
  const sampleLegalCases = [
    {
      title: 'Defective Electric Appliance Refund Dispute',
      text: 'The petitioner purchased a fully-integrated automatic washing machine of Brand X costing INR 45,000 on 12th Oct 2024. Within 3 weeks of purchase, the electronic drum malfunctioned and began releasing electric current during operation, rendering it high hazard. Despite repeated complaints, the retail vendor declined replacements, claiming user hardware overload. Service notes indicate manufacturing defect.',
      predictedOutcome: 'Ruled in Favor of Petitioner (Customer)',
      confidence: '89.2%',
      recommendedRemedy: 'Complete replacement of defect appliance or complete refund of INR 45,000 along with INR 10,000 punitive damages for mental distress.',
    },
    {
      title: 'Wrongful Health Insurance Claim Rejection',
      text: 'The complainant holds a genuine health insurance policy with Policy-Y for the last 5 years. After undergoing emergency cardiac block surgery at an empanelled hospital on 14th January 2025, the insurer rejected the cashless reimbursement claim of INR 3,20,000, citing undisclosed congenital pre-existing illness. However, independent medical certificate verifies the condition was sudden onset.',
      predictedOutcome: 'Ruled in Favor of Petitioner (Customer)',
      confidence: '86.4%',
      recommendedRemedy: 'Directs Insurer-Y to settle the full claim sum of INR 3,20,000 with 9% annual interest from the date of rejection, plus INR 15,000 litigation fees.',
    },
  ];

  // Civic pre-sets
  const [civicReport, setCivicReport] = useState({
    title: 'Open Deep Pothole on Main Crossing',
    description: 'A deep pothole has opened near the zebra crossing of Sector C block lane. It is flooded with water and causing riders to skid during evening hours.',
    urgency: 'high',
    location: '22.7196° N, 75.8577° E (Indore Sector C)',
    department: 'Department of Municipal Roads & Works',
    ocrDetected: 'WARNING: POTHOLE HAZARD ZONE / DEPTH > 15CM',
  });
  const [civicSubmitted, setCivicSubmitted] = useState(false);
  const [civicStatus, setCivicStatus] = useState('En-route');

  const [copiedDraft, setCopiedDraft] = useState(false);

  if (!isOpen || !project) return null;

  const runLegalPipeline = () => {
    setActiveTab('processing');
    setTimeout(() => {
      setActiveTab('results');
    }, 2200);
  };

  const runCivicSubmission = (e: React.FormEvent) => {
    e.preventDefault();
    setCivicSubmitted(true);
    setCivicStatus('Ingesting Report');
    setTimeout(() => {
      setCivicStatus('OCR Categorized');
    }, 1000);
    setTimeout(() => {
      setCivicStatus('Assigned to Local engineer');
    }, 2000);
  };

  const getCustomLegalReport = () => {
    const activeCase = sampleLegalCases[selectedCaseIdx];
    return `
=== INDIAN CONSUMER FORUM DRAFT REPORT ===
Generated by: Indian Law NLP Ensemble Model
Dataset Reference: NyayaAnumana Dataset

JUDGMENT PREDICTION: ${activeCase.predictedOutcome}
Ensemble Vote Confidence: ${activeCase.confidence}
Recommended Redressal: ${activeCase.recommendedRemedy}

STATEMENT OF REASONS:
The tribunal finds the respondent in clear violation of Consumer Protection Act specifications on grounds of unfair trade practice. Natural justice dictates full restoration of petitioner capital. 
=========================================
    `;
  };

  const handleCopyDraft = () => {
    navigator.clipboard.writeText(getCustomLegalReport());
    setCopiedDraft(true);
    setTimeout(() => setCopiedDraft(false), 2000);
  };

  const activeCase = sampleLegalCases[selectedCaseIdx];

  return (
    <div className="fixed inset-0 z-50 overflow-y-auto flex items-center justify-center p-4">
      {/* Backdrop */}
      <div className="fixed inset-0 bg-slate-900/60 backdrop-blur-xs" onClick={onClose} />

      {/* Modal Card */}
      <motion.div
        initial={{ opacity: 0, scale: 0.95, y: 15 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        exit={{ opacity: 0, scale: 0.95 }}
        className="relative bg-white dark:bg-slate-900 w-full max-w-3xl rounded-3xl shadow-2xl overflow-hidden border border-gray-200 dark:border-slate-800 z-10 flex flex-col max-h-[90vh]"
      >
        {/* Header bar */}
        <div className="px-6 py-4 border-b border-gray-200/60 dark:border-slate-800/60 bg-gray-50 dark:bg-slate-950 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <span className="w-2.5 h-2.5 rounded-full bg-blue-600 animate-pulse" />
            <span className="font-mono text-xs font-semibold text-gray-500 dark:text-slate-400 uppercase tracking-wider">
              {project.id === 'civicops' ? 'Civic Tech Sandbox' : 'ML Model Pipeline Simulator'}
            </span>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-gray-400 hover:bg-gray-200 dark:hover:bg-slate-800 dark:text-slate-500 transition-colors cursor-pointer"
          >
            <X size={18} />
          </button>
        </div>

        {/* Content Panel */}
        <div className="flex-1 overflow-y-auto p-6 sm:p-8">
          
          {/* SCRIPT A: LEGAL JUDGMENT PREDICTION SIMULATOR */}
          {project.id === 'legal-judgment-prediction' && (
            <div className="space-y-6 text-left">
              
              {/* Introduction Details */}
              <div className="p-4 rounded-2xl bg-blue-50/50 dark:bg-blue-950/20 border border-blue-100/50 dark:border-blue-900/30 flex gap-3">
                <Info className="text-blue-500 shrink-0 mt-0.5" size={16} />
                <div className="space-y-1">
                  <h4 className="font-sans font-bold text-xs text-blue-900 dark:text-blue-300">
                    NyayaAnumana Dataset Ensemble Pipeline
                  </h4>
                  <p className="font-sans text-[11px] text-blue-700 dark:text-blue-400 leading-normal">
                    This playground simulates an NLP pipeline evaluating draft complaint sheets in Indian language layouts. TF-IDF acts as vocabulary vectors, routing into weights processing which fuses classic parameters with bidirectional LSTM cell outputs.
                  </p>
                </div>
              </div>

              {activeTab === 'case-select' && (
                <div className="space-y-5">
                  {/* Step label */}
                  <div>
                    <span className="font-mono text-[9px] font-bold text-gray-400 uppercase">Step 1 of 3</span>
                    <h4 className="font-sans font-bold text-base text-gray-900 dark:text-white mt-0.5">
                      Select or Write Consumer Court Complaint
                    </h4>
                  </div>

                  {/* Pre-sets selections */}
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                    {sampleLegalCases.map((cse, idx) => (
                      <button
                        key={idx}
                        onClick={() => setSelectedCaseIdx(idx)}
                        className={`p-4 rounded-xl border text-left cursor-pointer transition-all ${
                          selectedCaseIdx === idx
                            ? 'bg-blue-50/35 dark:bg-blue-950/15 border-blue-600 dark:border-blue-500 ring-1 ring-blue-500/20'
                            : 'bg-white dark:bg-slate-800/40 border-gray-200/60 dark:border-slate-800 hover:border-gray-300'
                        }`}
                      >
                        <h5 className="font-sans font-bold text-xs text-gray-900 dark:text-white">
                          {cse.title}
                        </h5>
                        <p className="font-sans text-[11px] text-gray-500 dark:text-slate-400 truncate mt-1">
                          {cse.text}
                        </p>
                      </button>
                    ))}
                  </div>

                  {/* Complaint Text Box */}
                  <div className="space-y-1.5">
                    <span className="block font-sans text-xs font-semibold text-gray-700 dark:text-slate-300">
                      Complaint Narrative Details (Draft Context)
                    </span>
                    <textarea
                      value={customText || sampleLegalCases[selectedCaseIdx].text}
                      onChange={(e) => setCustomText(e.target.value)}
                      rows={4}
                      className="w-full text-xs sm:text-sm p-3 border border-gray-200 dark:border-slate-800 bg-transparent text-gray-850 dark:text-gray-250 outline-hidden focus:border-blue-600 rounded-xl leading-relaxed resize-none"
                    />
                  </div>

                  {/* Models Selection Checkboxes */}
                  <div className="space-y-2">
                    <span className="block font-sans text-xs font-semibold text-gray-700 dark:text-slate-300">
                      Ensemble Voter Models:
                    </span>
                    <div className="flex flex-wrap gap-3">
                      {Object.keys(selectedModels).map((modKey) => (
                        <label
                          key={modKey}
                          className="flex items-center gap-2 p-2.5 rounded-xl border border-gray-200/50 dark:border-slate-800 text-xs font-medium bg-gray-50/50 dark:bg-slate-900 select-none"
                        >
                          <input
                            type="checkbox"
                            checked={(selectedModels as any)[modKey]}
                            onChange={() =>
                              setSelectedModels({
                                ...selectedModels,
                                [modKey]: !(selectedModels as any)[modKey],
                              })
                            }
                            className="text-blue-600 focus:ring-blue-500 border-gray-300 rounded"
                          />
                          <span className="font-sans text-gray-750 dark:text-slate-300">
                            {modKey === 'logisticRegression' && 'Logistic Regression'}
                            {modKey === 'naiveBayes' && 'Multinomial Naive Bayes'}
                            {modKey === 'xgboost' && 'XGBoost Classification'}
                            {modKey === 'bilstm' && 'Bidirectional LSTM (NN)'}
                          </span>
                        </label>
                      ))}
                    </div>
                  </div>

                  {/* Submit Trigger */}
                  <button
                    onClick={runLegalPipeline}
                    className="w-full py-2.5 rounded-xl bg-blue-600 hover:bg-blue-700 text-white font-sans font-semibold text-xs sm:text-sm flex items-center justify-center gap-2 cursor-pointer transition-colors mt-2"
                  >
                    <Play size={14} />
                    <span>Compile &amp; Process NLP Ensemble Pipeline</span>
                  </button>
                </div>
              )}

              {activeTab === 'processing' && (
                <div className="py-12 flex flex-col items-center justify-center space-y-6 text-center">
                  <div className="relative">
                    <div className="w-16 h-16 rounded-full border-4 border-blue-100 dark:border-slate-800 border-t-blue-600 animate-spin" />
                    <Cpu className="absolute inset-0 m-auto text-blue-600" size={24} />
                  </div>

                  <div className="space-y-2">
                    <h4 className="font-sans font-bold text-gray-900 dark:text-white text-base">
                      Running Prediction Ensemble Graph
                    </h4>
                    
                    <div className="max-w-xs mx-auto space-y-1.5 font-mono text-[10px] text-gray-400 dark:text-slate-400 text-left bg-gray-50 dark:bg-slate-900 p-4 border border-gray-150 dark:border-slate-800/80 rounded-xl">
                      <p className="flex items-center gap-2"><span className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-ping"/> Tokenizing Complaint Words...</p>
                      <p className="flex items-center gap-2"><span className="w-1.5 h-1.5 rounded-full bg-blue-500 animate-pulse"/> Ingesting pre-trained TF-IDF...</p>
                      <p className="flex items-center gap-2"><span className="w-1.5 h-1.5 rounded-full bg-indigo-500 animate-pulse"/> Standardizing sequence layers...</p>
                      <p className="flex items-center gap-2"><span className="w-1.5 h-1.5 rounded-full bg-pink-500 animate-pulse"/> Ingesting BiLSTM cell outputs...</p>
                      <p className="flex items-center gap-2"><span className="w-1.5 h-1.5 rounded-full bg-amber-500 animate-pulse"/> Calculating probability votes...</p>
                    </div>
                  </div>
                </div>
              )}

              {activeTab === 'results' && (
                <div className="space-y-6">
                  {/* Step label */}
                  <div>
                    <span className="font-mono text-[9px] font-bold text-emerald-500 uppercase">Step 3 of 3 • Success</span>
                    <h4 className="font-sans font-bold text-lg text-gray-900 dark:text-white mt-0.5">
                      AI judgment Prediction Output
                    </h4>
                  </div>

                  {/* Core scorecard */}
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    {/* Prediction output */}
                    <div className="p-4 rounded-2xl bg-emerald-50/55 dark:bg-emerald-950/20 border border-emerald-100 dark:border-emerald-900/30 flex items-start gap-3">
                      <CheckCircle2 className="text-emerald-500 shrink-0 mt-0.5" size={22} />
                      <div>
                        <span className="block font-mono text-[9px] text-gray-400 dark:text-slate-500 uppercase font-semibold">
                          Classified predicted outcome
                        </span>
                        <span className="block font-sans font-bold text-sm sm:text-base text-emerald-700 dark:text-emerald-400 mt-0.5">
                          {activeCase.predictedOutcome}
                        </span>
                      </div>
                    </div>

                    {/* Confidence percentage */}
                    <div className="p-4 rounded-2xl bg-blue-50/50 dark:bg-slate-900 border border-gray-200/60 dark:border-slate-800 flex items-start gap-3">
                      <BarChart className="text-blue-500 shrink-0 mt-0.5" size={22} />
                      <div>
                        <span className="block font-mono text-[9px] text-gray-400 dark:text-slate-500 uppercase font-semibold">
                          Calculated Confidence Interval
                        </span>
                        <span className="block font-serif font-extrabold text-sm sm:text-base text-blue-600 dark:text-blue-400 mt-0.5">
                          {activeCase.confidence}
                        </span>
                      </div>
                    </div>
                  </div>

                  {/* Recommended redresses text */}
                  <div className="p-4 rounded-2xl bg-gray-50 dark:bg-slate-900 border border-gray-250 dark:border-slate-800 text-left">
                    <span className="block font-mono text-[10px] font-bold text-gray-400 uppercase mb-1">
                      Recommended Redressal Remedy
                    </span>
                    <p className="font-sans text-xs sm:text-sm text-gray-700 dark:text-slate-300 leading-relaxed font-medium">
                      {activeCase.recommendedRemedy}
                    </p>
                  </div>

                  {/* Indian law report sheet download block */}
                  <div className="border border-gray-200 dark:border-slate-800 rounded-2xl overflow-hidden bg-gray-50/50 dark:bg-slate-950/50">
                    <div className="px-4 py-3 bg-gray-100 dark:bg-slate-900 flex items-center justify-between border-b border-gray-200 dark:border-slate-800">
                      <span className="font-mono text-[10px] text-gray-500">CONSUMER_COURT_DRAFT.TXT</span>
                      <button
                        onClick={handleCopyDraft}
                        className="px-2.5 py-1 rounded bg-white dark:bg-slate-800 border border-gray-200 dark:border-slate-700 font-sans font-semibold text-[10px] flex items-center gap-1.5 cursor-pointer text-gray-700 dark:text-slate-300"
                      >
                        {copiedDraft ? <CheckCircle2 size={11} className="text-emerald-500" /> : <Copy size={11} />}
                        <span>{copiedDraft ? 'Copied' : 'Copy'}</span>
                      </button>
                    </div>
                    <pre className="p-4 font-mono text-[10px] text-gray-600 dark:text-slate-400 leading-normal overflow-x-auto text-left whitespace-pre-wrap">
                      {getCustomLegalReport()}
                    </pre>
                  </div>

                  {/* Restart button */}
                  <button
                    onClick={() => setActiveTab('case-select')}
                    className="px-4 py-2 bg-white dark:bg-slate-800 text-gray-700 dark:text-slate-300 border border-gray-250 dark:border-slate-700 font-sans text-xs font-semibold rounded-xl flex items-center gap-1.5 hover:bg-gray-50 cursor-pointer ml-auto"
                  >
                    <RefreshCw size={12} />
                    <span>Evaluate Different complaint</span>
                  </button>

                </div>
              )}
            </div>
          )}


          {/* SCRIPT B: CIVICOPS INTERACTIVE REPORTER SANDBOX */}
          {project.id === 'civicops' && (
            <div className="space-y-6 text-left">
              
              <div className="p-4 rounded-2xl bg-blue-50/50 dark:bg-blue-950/20 border border-blue-100/50 dark:border-blue-900/30 flex gap-3">
                <Info className="text-blue-500 shrink-0 mt-0.5" size={16} />
                <div className="space-y-1">
                  <h4 className="font-sans font-bold text-xs text-blue-900 dark:text-blue-300">
                    CiviCops Crowdsource Reporting Node
                  </h4>
                  <p className="font-sans text-[11px] text-blue-700 dark:text-blue-400 leading-normal">
                    Designed to demonstrate live OCR capture and geo-tagged coordination. When reported, municipal networks ingest target parameters and calculate optimal department routings.
                  </p>
                </div>
              </div>

              {!civicSubmitted ? (
                <form onSubmit={runCivicSubmission} className="space-y-5">
                  <div>
                    <span className="font-mono text-[9px] text-gray-400 uppercase font-semibold">Incident Submission Chamber</span>
                    <h4 className="font-sans font-bold text-base text-gray-900 dark:text-white mt-0.5">
                      Log New Municipal Grievance Report
                    </h4>
                  </div>

                  <div className="space-y-4">
                    {/* Issue Subject Title */}
                    <div className="space-y-1.5">
                      <label className="block font-sans text-xs font-semibold text-gray-700 dark:text-slate-300">
                        Issue Title
                      </label>
                      <input
                        type="text"
                        value={civicReport.title}
                        onChange={(e) => setCivicReport({ ...civicReport, title: e.target.value })}
                        className="w-full text-xs sm:text-sm p-3 border border-gray-200 dark:border-slate-800 bg-transparent text-gray-800 dark:text-white outline-hidden focus:border-blue-600 rounded-xl"
                        required
                      />
                    </div>

                    {/* Complaint detailed descriptions */}
                    <div className="space-y-1.5">
                      <label className="block font-sans text-xs font-semibold text-gray-700 dark:text-slate-300">
                        Incident Details
                      </label>
                      <textarea
                        value={civicReport.description}
                        onChange={(e) => setCivicReport({ ...civicReport, description: e.target.value })}
                        rows={3}
                        className="w-full text-xs sm:text-sm p-3 border border-gray-200 dark:border-slate-800 bg-transparent text-gray-800 dark:text-white outline-hidden focus:border-blue-600 rounded-xl leading-relaxed resize-none"
                        required
                      />
                    </div>

                    {/* Meta geo tags & pictures */}
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                      {/* GPS Meta */}
                      <div className="space-y-1.5">
                        <label className="block font-sans text-xs font-semibold text-gray-700 dark:text-slate-300 flex items-center gap-1.5">
                          <MapPin size={13} className="text-gray-400" /> GPS Tag (Geo-location)
                        </label>
                        <input
                          type="text"
                          value={civicReport.location}
                          onChange={(e) => setCivicReport({ ...civicReport, location: e.target.value })}
                          className="w-full font-mono text-xs p-3 border border-gray-200 dark:border-slate-800 bg-transparent text-gray-800 dark:text-white outline-hidden focus:border-blue-600 rounded-xl"
                        />
                      </div>

                      {/* Mock Photo Camera field */}
                      <div className="space-y-1.5">
                        <span className="block font-sans text-xs font-semibold text-gray-700 dark:text-slate-300 flex items-center gap-1.5">
                          <Camera size={13} className="text-gray-400" /> Uploaded Visual Photo
                        </span>
                        <div className="p-3 border border-dashed border-gray-200 dark:border-slate-800 rounded-xl flex items-center justify-center text-xs text-blue-600 dark:text-blue-400 bg-gray-50/50 dark:bg-slate-900/50 font-medium">
                          <span>pothole_crossed_05.jpg (Camera feed ok)</span>
                        </div>
                      </div>
                    </div>
                  </div>

                  <button
                    type="submit"
                    className="w-full py-2.5 rounded-xl bg-blue-600 hover:bg-blue-700 text-white font-sans font-semibold text-xs sm:text-sm flex items-center justify-center gap-2 cursor-pointer transition-colors"
                  >
                    <span>Dispatch Crowdsourced Incident Ticket</span>
                  </button>

                </form>
              ) : (
                <div className="space-y-6">
                  {/* Connected Success Output */}
                  <div className="p-5 rounded-2xl bg-emerald-50/50 dark:bg-emerald-950/10 border border-emerald-100 dark:border-emerald-900/30 flex items-start gap-4">
                    <CheckCircle2 size={24} className="text-emerald-500 shrink-0 mt-0.5" />
                    <div className="space-y-1">
                      <h4 className="font-sans font-bold text-sm sm:text-base text-gray-900 dark:text-white">
                        Civic Incident Registered Securely
                      </h4>
                      <p className="font-sans text-xs text-gray-600 dark:text-slate-450 leading-relaxed">
                        Ticket UUID: CC-8749-301. Automated routing algorithm computed and targeted key municipal nodes instantly.
                      </p>
                    </div>
                  </div>

                  {/* Pipeline state steps visualization */}
                  <div className="relative pt-4 text-xs font-sans text-left space-y-4">
                    <span className="block font-mono text-[10px] text-gray-400 uppercase font-semibold">
                      Live Ingest Network States:
                    </span>

                    <div className="space-y-3.5 pl-6 border-l border-gray-250 dark:border-slate-800 relative">
                      {/* En route */}
                      <div className="relative">
                        <div className="absolute -left-[29px] top-0.5 w-3 h-3 rounded-full bg-emerald-500 border-2 border-white dark:border-slate-900" />
                        <span className="font-semibold text-gray-950 dark:text-white">1. Grievance Ingested</span>
                        <p className="text-[11px] text-gray-500 dark:text-slate-400 mt-1">Geo-tag checks located coordinates within target zone municipal boundaries successfully.</p>
                      </div>

                      {/* OCR Categorized */}
                      <div className="relative">
                        <div className={`absolute -left-[29px] top-0.5 w-3 h-3 rounded-full border-2 border-white dark:border-slate-900 ${civicStatus !== 'Ingesting Report' ? 'bg-emerald-500' : 'bg-gray-300'}`} />
                        <span className={`font-semibold ${civicStatus !== 'Ingesting Report' ? 'text-gray-950 dark:text-white' : 'text-gray-400'}`}>2. NLP / OCR OCR Classification Block</span>
                        <p className="text-[11px] text-gray-500 dark:text-slate-400 mt-1">OCR scanned visual reports. Log: <code className="bg-gray-100 dark:bg-slate-950 px-1 py-0.5 rounded font-mono text-[9px] text-rose-500">{civicReport.ocrDetected}</code></p>
                      </div>

                      {/* Routed */}
                      <div className="relative">
                        <div className={`absolute -left-[29px] top-0.5 w-3 h-3 rounded-full border-2 border-white dark:border-slate-900 ${civicStatus === 'Assigned to Local engineer' ? 'bg-emerald-500' : 'bg-gray-300'}`} />
                        <span className={`font-semibold ${civicStatus === 'Assigned to Local engineer' ? 'text-gray-950 dark:text-white' : 'text-gray-400'}`}>3. Target Node Routing Success</span>
                        <p className="text-[11px] text-gray-500 dark:text-slate-400 mt-1">Routed to <strong className="text-blue-600 dark:text-blue-400 font-medium">{civicReport.department}</strong> on duty.</p>
                      </div>
                    </div>
                  </div>

                  {/* Control row */}
                  <div className="flex justify-between items-center pt-4 border-t border-gray-150 dark:border-slate-800/80">
                    <span className="font-mono text-[9px] text-gray-400 uppercase">
                      Current Node State: {civicStatus}
                    </span>

                    <button
                      onClick={() => setCivicSubmitted(false)}
                      className="px-4 py-2 bg-white dark:bg-slate-800 text-gray-700 dark:text-slate-300 border border-gray-250 dark:border-slate-700 font-sans text-xs font-semibold rounded-xl flex items-center gap-1.5 hover:bg-gray-50 cursor-pointer"
                    >
                      <RefreshCw size={12} />
                      <span>Create Another Ticket</span>
                    </button>
                  </div>

                </div>
              )}

            </div>
          )}

        </div>
      </motion.div>
    </div>
  );
}
